name: Sync Backend to Hugging Face
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:  # This line is key
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action"

          # The "magic" command: split the backend folder and force-push it in one go
          git push https://saad-muhammad:$HF_TOKEN@huggingface.co/spaces/saad-muhammad/saad-muhammad/Test_on_new_branch `git subtree split --prefix backend feature/deepface-migration`:main --force

 